### ISSUE TITLE
Readme bug

### ISSUE THREAD

**Issue by shadowbourne** [BatsResearch/nayak-arxiv20-code#1]
Within https://github.com/BatsResearch/nayak-arxiv20-code/blob/20fc65c7f0b5aa5cbb57b53a827eeb48451d2d31/object_classification/README.md
Im assuming ## Setup should be 
```
mkdir data/subgraphs
cd data/subgraphs
```
rather than 
```
mkdir data
cd data/subgraphs
```
?

As, as it currently stands, the setup makes no sense?

**Comment by nihalnayak** [comment]
Thanks for pointing out the bug. I have fixed this issue :)
