### ISSUE TITLE
issue about ’materials/resnet50-base.pth‘

### ISSUE THREAD

**Issue by DoubleClass** [BatsResearch/nayak-arxiv20-code#16]
Is The materials/resnet50-base.pth used in finetuning process refers to the parameters from the first training phase? My understanding is that during the first training stage, the ResNet-50 pretrained parameters were not modified, so this can be used directly.

**Comment by nihalnayak** [comment]
Yes! As mentioned in Appendix J2 of the paper, we keep the ResNet50 model frozen when minimizing the L2 distance between the learned class representations and the weights of the fully connected layer. Then, in the second stage, we freeze the class representations and fine-tune the ResNet50 backbone.
