### ISSUE TITLE
AWA2 training Flow query

### ISSUE THREAD

**Issue by shadowbourne** [BatsResearch/nayak-arxiv20-code#2]
I am slightly confused what happens after train.py?
As in the paper it suggests: 
> Following prior work (Kampffmeyer et al.,
2019; Wang et al., 2018), we learn class representations by
minimizing the L2 distance between the learn class representations and the weights of the fully connected layer of
a ResNet classifier pretrained on the ILSVRC 2012. **Next,
we freeze the class representations and finetune the ResNetbackbone on the training images from the dataset.**

So this would suggest we run train, then finetune, then evauluate_awa2? is this correct?

Going to look in more detail tomorrow I just want to make sure I am not diving down the wrong rabbit hole as I struggled to see how finetune and evaulate.py interacted at all when I looked earlier.

Forgive me if I am being stupid and thanks for your help!!

**Comment by nihalnayak** [comment]
Thanks for reaching out. Yes, you are right.

**Comment by shadowbourne** [comment]
Okay so I think I understand why I was so confused.
I believe you have accidentally committed nayak-arxiv20-code\object_classification\evaluate_awa2.py twice!
As nayak-arxiv20-code\object_classification\finetune_awa2.py has only 1 line which is different to evaluate_awa2.py which is:
![image](https://user-images.githubusercontent.com/18665030/143457458-d8daeba7-1a9d-4930-8e0e-0ba4709325ab.png)

**Comment by nihalnayak** [comment]
@shadowbourne Oops. I may have accidentally copied the code twice. I have resolved this issue on the repo.
