### ISSUE TITLE
Instructions to download ConceptNetDB.

### ISSUE THREAD

**Issue by nihalnayak** [BatsResearch/nayak-arxiv20-code#5]
Include instructions on how to download ConceptNetDB from https://github.com/BatsResearch/taglets. This will help people experiment with custom graphs and classes. 

File to download:
```
wget -nc https://storage.googleapis.com/taglets-public/scads.spring2021.sqlite3
```

**Comment by Youmna-Salah** [comment]
Great! Thank you for the links and the resources! I still have another issue but not related to that, I will open another issue to avoid confusion.

**Comment by nihalnayak** [comment]
Perfect!
