### ISSUE TITLE
kg.rw_adj_lists does not contain adjacency information for all the nodes defined as keys in SYNS

### ISSUE THREAD

**Issue by pathpot** [BatsResearch/nayak-arxiv20-code#8]
Hi,

I would like to run your training pipeline on my custom subset of AWA2. Basically, I replace IMAGENET_SYNS in https://github.com/BatsResearch/nayak-arxiv20-code/blob/master/graph_utils/main.py with my sync (defined in awa2_syns.py in the attachment) for the graph generation.

The problem is that, not all the nodes in the generated graphs have information as keys in in kg.rw_adj_lists. This would cause the problem when I run https://github.com/BatsResearch/nayak-arxiv20-code/blob/master/object_classification/train.py with this generated graph and my version of awa_concepts.txt (also in the attachment). When rw_adj_lists do not have adjacency information as keys for my nodes, this would trigger an exception on the line 116 in https://github.com/BatsResearch/zsl-kg/blob/master/zsl_kg/common/graph.py.

I expect that kg.rw_adj_lists should have adjacency lists at least for all my nodes from keys defined in SYNS. Is this a bug of the code or I misunderstand something?

Thank you in advance,

Piyapat

[attachment.zip](https://github.com/BatsResearch/nayak-arxiv20-code/files/7974191/attachment.zip)

**Comment by nihalnayak** [comment]
Thank you for the question. You are right that all the nodes may not be present in `kg.rw_adj_lists`. This could happen for two reasons: 

1. The synonym node was not found in the conceptnet graph. You can add a self-loop to the list of edges if the node doesn't exist. You can define the missing nodes in the nodes list and a self-loop relation in the relations list. Then, add edges with self-loop `(u, r, u)` to the edges list. It might be just a few lines of preprocessing after querying the graph. 

2. The synonym is merged with the key. For example, `/c/en/goldfish/n` and `/c/en/goldfish/n/wn/animal` will be merged with `/c/en/goldfish`. I am merging the primary node and its synonyms when I am querying the graph in https://github.com/BatsResearch/nayak-arxiv20-code/blob/d7277157e832a683fbd375fa154c0c91f8df2952/graph_utils/query.py. 
```python
    # replace edges list with the syn ids
    edges = []
    for start_id, end_id, relation_id, _ in edges_list:

        if start_id in syn_id_to_node_id:
            start_id = syn_id_to_node_id[start_id]

        if end_id in syn_id_to_node_id:
            end_id = syn_id_to_node_id[end_id]

        edges.append((start_id, relation_id, end_id))

```
You may want to remove these lines if you want access to all your synonyms as a separate node in `kg.rw_adj_lists`. 

I hope this helps! Good luck!

**Comment by pathpot** [comment]
I have tried adding the self-loop by adding the code below after the call of `nodes, edges, relations = query_conceptnet(syns, database_path)`:

```
    sl_rel_id = 50
    relations = relations.append(
        pd.DataFrame([[sl_rel_id, '/r/SelfLoop', 0]], columns=['id', 'uri', 'directed']),
        ignore_index=True)
    for node_id in list(nodes['id']):
        edges = edges.append(
            pd.DataFrame([[node_id, sl_rel_id, node_id]], columns=['start_id', 'relation_id', 'end_id']),
            ignore_index=True)
```

However, the problem (exception on the line 116 during train.py) still persist. I added a debug line after graph generation to print messages after the random walk:

```
    print('N Walks: ', len(kg.rw_adj_lists))
    print('N Nodes: ', len(kg.nodes))
```

And got this number in my case:

```
N Walks:  15817
N Nodes:  175413
```

The length of rw_adj_list is too low indicating that most of the nodes still do not have their keys in rw_adj_list. Did I make any mistakes? Could you suggest how to make rw_adj_list available for my preferred nodes correctly?

Cheers,

Piyapat

**Comment by nihalnayak** [comment]
Hi Piyapat,

Thanks for pointing out this bug. I have included the fix for your issue in https://github.com/BatsResearch/nayak-arxiv20-code/tree/fix-self-loop. Can you check if it works for you? 

The edges are remapped starting from 0. I was previously remapping edges in another file but I may have missed including this snippet in the code during the cleanup.

**Comment by pathpot** [comment]
Hi,

This branch seems to fix my issue. Thank you very much for your help :)
